# StyleChecker's Travis configuration
language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk14

services:
  - mysql
before_script:
  - mysql -u root --password="" < src/test/travis.sql

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build --scan -s



#install:
#  - mvn -N io.takari:maven:wrapper
#  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#
#script:
#  - mvn test



