# StyleChecker's Travis configuration
language: java
sudo: false

services:
  - mysql
before_script:
  - mysql -u root --password="" < src/test/travis.sql

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test
