package com.example.YESserver;

import com.example.YESserver.models.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.security.Principal;
import java.sql.*;

@RestController // This means that this class is a Controller

// @RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)

public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping("/")
    public String home() {
        return ("<h1>Welcome</h1>");
    }

    @GetMapping(path="/user")
    public String user(Principal principal) {
        return ("<h1>Welcome User " + principal.getName() + "</h1>");
    }

    @GetMapping(path="/admin")
    public String admin(Principal principal) {
        return ("<h1>Welcome Admin " + principal.getName() + "</h1>");
    }

    @GetMapping(path="/instructor")
    public String instructor(Principal principal) {
        return ("<h1>Welcome Instructor " + principal.getName() + "</h1>");
    }

    @GetMapping(path="/student")
    public String student(Principal principal) {
        return ("<h1>Welcome Student " + principal.getName() + "</h1>");
    }









    // The following mappings are for the catalog


    @GetMapping(path="/catalog")
    public String catalog() throws SQLException {
        // This returns a JSON or XML with the users
        Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/yes_database","root","");

        Statement stmt = con.createStatement();
        try {
            ResultSet rs = stmt.executeQuery("Select * from courses");

            return viewTable(rs, "Course Catalog");

        }
        catch (Exception e) {
            return "Error";
        }
    }

    @GetMapping(path="/catalog/{course_category}")
    public String catalog_with_category(@PathVariable("course_category") String category) throws SQLException {
        // This returns a JSON or XML with the users
        Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/yes_database","root","");

        Statement stmt = con.createStatement();

        try {
            ResultSet rs = stmt.executeQuery("Select * from courses where course_category = " + category);

            return viewTable(rs, "Course Catalog for " + category + " courses");

        }
        catch (Exception e) {
            return "Error";
        }
    }

    @GetMapping(path="/catalog/space_available")
    public String catalog_space_available() throws SQLException {
        // This returns a JSON or XML with the users
        Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/yes_database","root","");

        Statement stmt = con.createStatement();
        try {
            ResultSet rs = stmt.executeQuery("Select * from courses where not total_enrolled = class_capacity");

            return viewTable(rs, "Courses that have available spaces");

        }
        catch (Exception e) {
            return "Error";
        }
    }

    @GetMapping(path="/catalog/waitlist_available")
    public String catalog_waitlist_available() throws SQLException {
        // This returns a JSON or XML with the users
        Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/yes_database","root","");

        Statement stmt = con.createStatement();
        try {
            ResultSet rs = stmt.executeQuery("Select * from courses where total_enrolled = class_capacity " +
                    "and total_enrolled > 0 and not total_on_waitlist = waitlist_capacity");

            return viewTable(rs, "Courses that have available waitlist spaces");

        }
        catch (Exception e) {
            return "Error";
        }
    }

    @GetMapping(path="/catalog/closed_courses")
    public String catalog_closed_courses() throws SQLException {
        // This returns a JSON or XML with the users
        Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/yes_database","root","");

        Statement stmt = con.createStatement();
        try {
            ResultSet rs = stmt.executeQuery("Select * from courses where total_on_waitlist = waitlist_capacity " +
                    "and not total_on_waitlist = 0");

            return viewTable(rs, "Courses that are closed");

        }
        catch (Exception e) {
            return "Error";
        }
    }

    public String viewTable(ResultSet rs, String title) throws SQLException {
        StringBuilder result = new StringBuilder();

        result.append("<table border=\"1\" \nalign=\"left\"> \n<caption>").append(title).append("</caption>");
        ResultSetMetaData rsmd = rs.getMetaData();

        int columnsNumber = rsmd.getColumnCount();

        result.append("<tr>");
        for (int i = 1; i <= columnsNumber; i++) {
            result.append("<th>").append(rsmd.getColumnName(i)).append("</th>");
        }
        result.append("</tr>");


        while (rs.next()) {
            result.append("<tr>");
            for (int i = 1; i <= columnsNumber; i++) {
                result.append("<td>").append(rs.getString(i)).append("</td>");
            }
            result.append("</tr>");
        }

        result.append("</table>");

        return result.toString();
    }










    // The following mappings are for the schedule


    @GetMapping(path="/schedule")
    public String schedule(Principal principal) throws SQLException {
        String user = principal.getName();

        // This returns a JSON or XML with the users
        Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/yes_database","root","");

        Statement stmt = con.createStatement();

        try {
            ResultSet rs = stmt.executeQuery("Select schedules.course_id, schedules.course_status from courses " +
                    "inner join schedules where schedules.course_status in('enrolled', 'waitlisted', 'instructing') " +
                    "and schedules.course_id = courses.course_id and schedules.user_id = \"" + user + "\"");

            return viewTable(rs, "Your Enrolled or Waitlisted Courses");

        }
        catch (Exception e) {
            return "Error";
        }
    }

    @GetMapping(path="/cart")
    public String cart(Principal principal) throws SQLException {
        String user = principal.getName();

        // This returns a JSON or XML with the users
        Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/yes_database","root","");

        Statement stmt = con.createStatement();

        try {
            ResultSet rs = stmt.executeQuery("Select schedules.course_id, schedules.course_status from courses " +
                    "inner join schedules where schedules.course_status = 'cart' " +
                    "and schedules.course_id = courses.course_id and schedules.user_id = \"" + user + "\"");

            return viewTable(rs, "Your Courses in Cart");

        }
        catch (Exception e) {
            return "Error";
        }
    }

    @GetMapping(path="/watching")
    public String watching(Principal principal) throws SQLException {
        String user = principal.getName();

        // This returns a JSON or XML with the users
        Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/yes_database","root","");

        Statement stmt = con.createStatement();

        try {
            ResultSet rs = stmt.executeQuery("Select schedules.course_id, schedules.course_status from courses " +
                    "inner join schedules where schedules.course_status = 'watching' " +
                    "and schedules.course_id = courses.course_id and schedules.user_id = \"" + user + "\"");

            return viewTable(rs, "Courses You are Watching");

        }
        catch (Exception e) {
            return "Error";
        }
    }













    // The following mappings are for the admin

    // example: http://localhost:8080/admin/add_course?course_id="MATH2500"&course_hour=3&course_category="Math"&description="Multivariable Calculus and Linear Algebra"&class_capacity=40&waitlist_capacity=12
    @PostMapping(path="/admin/add_course")
    public String add_course(@RequestParam("course_id") String course_id,
                             @RequestParam("course_hour") int course_hour,
                             @RequestParam("course_category") String course_category,
                             @RequestParam("description") String description,
                             @RequestParam("class_capacity") int class_capacity,
                             @RequestParam("waitlist_capacity") int waitlist_capacity) throws SQLException {
        Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/yes_database","root","");

        Statement stmt = con.createStatement();



        try {
            stmt.executeUpdate("INSERT INTO courses VALUES (" + course_id + ", " + course_hour + ", " +
                    course_category + ", " + description + ", 0, " + class_capacity + ", 0, " + waitlist_capacity + ")");

            return "Successfully added the course";

        }
        catch (Exception e) {
            return "Error";
        }
    }

    // example: http://localhost:8080/admin/remove_course?course_id="MATH2300"
    @PostMapping(path="/admin/remove_course")
    public String remove_course(@RequestParam("course_id") String course_id) throws SQLException {
        Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/yes_database","root","");

        Statement stmt = con.createStatement();

        try {
            stmt.executeUpdate("DELETE FROM courses WHERE course_id = " + course_id);

            return "Successfully added the course";

        }
        catch (Exception e) {
            return "Error";
        }
    }

    // example: http://localhost:8080/admin/add_user?username=Marina_Wang_01&password=marina1&role="student"&name="Marina_Wang"&email="marina.wang@vanderbilt.edu"
    @PostMapping(path="/admin/add_user") // Map ONLY POST Requests
    public String addNewUser (@RequestParam("username") String username,
                              @RequestParam("password") String password,
                              @RequestParam("role") String role,
                              @RequestParam("name") String name,
                              @RequestParam("email") String email) throws SQLException {

        Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/yes_database","root","");

        Statement stmt = con.createStatement();

        try {
            User n = new User();
            n.setUserName(username);
            n.setPassword(password);
            n.setActive(true);
            if (role.equals("\"student\"") || role.equals("\"instructor\"")) {
                n.setRoles("ROLE_USER");
            }
            else if (role.equals("\"admin\"")) {
                n.setRoles("ROLE_ADMIN");
            }
            else {
                return "Please enter a correct role type. It should be one of admin, student, or instructor. You entered " + role;
            }
            userRepository.save(n);


            stmt.executeUpdate("INSERT INTO users VALUES (\"" + username + "\", " + name + ", \"" +
                    password + "\", " + role + ", " + email + ")");

            return "Successfully added the user";

        }
        catch (Exception e) {
            return "Error";
        }
    }










//
//
//    // The following mappings are for the instructor
//
//
//    // example: http://localhost:8080/instructor/add_student_to_course?user_id="Acar_Ary_01"&course_id="MATH2300"
//    @PostMapping(path="/instructor/add_student_to_course")
//    public String add_student_to_course(@RequestParam("user_id") String user_id,
//                                        @RequestParam("course_id") String course_id) throws SQLException {
//        Connection con = DriverManager.getConnection(
//                "jdbc:mysql://localhost:3306/yes_database","root","");
//
//        Statement stmt = con.createStatement();
//
//
//
//        try {
//
//            if (EXISTS(SELECT 1 FROM dbo.Customer WITH(NOLOCK)
//                    WHERE CustId = @CustId)
//
//
//            stmt.executeUpdate("DELETE FROM courses WHERE user_id = " + user_id + " and course_if = " + course_id);
//
//            stmt.executeUpdate("INSERT INTO courses VALUES (" + user_id + ", " + course_id + ", 'enrolled')");
//
//            return "Successfully added the course";
//
//        }
//        catch (Exception e) {
//            return "Error";
//        }
//    }
//
//
















    @GetMapping(path="/all")
    public Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
